# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'floating Button' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for floating Button
pod 'Floaty', '~> 4.1.0'
end
